; Color constants
C_BLACK .equ %00000000
C_WHITE .equ %11111111
C_RED   .equ %11100000
C_GREEN .equ %00000011
C_BLUE  .equ %00011100
SPRITE_WIDTH .equ 16

TestSprite:
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
  .db C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK, C_RED, C_BLACK
