
#include "build/sprites/player.asm"
;#include "build/sprites/debug.asm"
#include "build/sprites/projectile.asm"
#include "build/sprites/enemy_death.asm"
#include "build/sprites/enemy_1a.asm"
#include "build/sprites/enemy_1b.asm"
#include "build/sprites/enemy_2a.asm"
#include "build/sprites/enemy_2b.asm"
#include "build/sprites/enemy_3a.asm"
#include "build/sprites/enemy_3b.asm"
